package presentacion;

import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Vista correspondiente a el método de rotación manual de un objeto, dando las coordenadas (X,Y,Z)
 * @author A3D Ingeniería
 */
public class VistaRotarManual extends javax.swing.JFrame {

    //Atributos
    private static ControladorVistaRotar control;

    /**
     * Crea la vista para rotar manualmente un objeto
     * @param control Controlador de la vista de rotar manual, que como su nombre indica, controla todo lo que tenga o capture la vista
     */
    public VistaRotarManual(ControladorVistaRotar control) {
        initComponents();
        this.setName("Rotación Manual");
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        labelEjeX = new javax.swing.JLabel();
        labelEjeY = new javax.swing.JLabel();
        labelEjeZ = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        xValue = new javax.swing.JTextField();
        yValue = new javax.swing.JTextField();
        zValue = new javax.swing.JTextField();
        helpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Introduzca los valores decimales (X, Y, Z) para rotar el objeto"));

        labelEjeX.setText("Eje X:");

        labelEjeY.setText("Eje Y:");

        labelEjeZ.setText("Eje Z:");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        xValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                xValueKeyTyped(evt);
            }
        });

        yValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yValueKeyTyped(evt);
            }
        });

        zValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zValueKeyTyped(evt);
            }
        });

        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelLayout = new org.jdesktop.layout.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLayout.createSequentialGroup()
                .add(64, 64, 64)
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(labelEjeY)
                    .add(labelEjeX)
                    .add(labelEjeZ))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(yValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(zValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(xValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(61, 61, Short.MAX_VALUE)
                .add(helpButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(68, 68, 68))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(cancelButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(okButton)
                .add(50, 50, 50))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLayout.createSequentialGroup()
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelLayout.createSequentialGroup()
                        .add(36, 36, 36)
                        .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(xValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelEjeX))
                        .add(18, 18, 18)
                        .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(yValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelEjeY)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(helpButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(zValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelEjeZ))
                .add(18, 18, 18)
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(cancelButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ImageIcon tmpIconAux = new ImageIcon(getClass().getResource("/resources/help.png"));
        ImageIcon tmpIcon = new ImageIcon(tmpIconAux.getImage().getScaledInstance(54, 54, Image.SCALE_DEFAULT));
        helpButton.setIcon(tmpIcon);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Gestiona la pulsación del botón OK de la vista para aplicar la rotación
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            control.getDesktop().getSelectedFrame().setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VistaRotarManual.class.getName()).log(Level.SEVERE, null, ex);
        }
        control.rotarManual(xValue.getText(), yValue.getText(), zValue.getText());
    }//GEN-LAST:event_okButtonActionPerformed

    //Gestiona el click del botón cancelar que aparece en la vista que cancela la rotación
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        control.cancelarRotacion();
    }//GEN-LAST:event_cancelButtonActionPerformed

    //Control del campo de las cordenadas X al introducir un nuevo carácter
    private void xValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xValueKeyTyped
        comprobarValores(xValue.getText());
    }//GEN-LAST:event_xValueKeyTyped

    //Control del campo de las cordenadas Y al introducir un nuevo carácter
    private void yValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yValueKeyTyped
        comprobarValores(yValue.getText());
    }//GEN-LAST:event_yValueKeyTyped

    //Control del campo de las cordenadas Z al introducir un nuevo carácter
    private void zValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zValueKeyTyped
        comprobarValores(zValue.getText());
    }//GEN-LAST:event_zValueKeyTyped

    //Gestión del botón de ayuda que aparece en la vista, cuando es presionado
    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Valor -> 2 ó 2.02 \n PARTE-ENTERA[.PARTE-DECIMAL] \n Vaya a la ayuda si sigue teniendo dudas.", "Valores decimales", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_helpButtonActionPerformed

    //Comprueba el valor introducido de un String
    private void comprobarValores(String valor) {
        boolean falso = false;
        if (valor.length() < 1) {
            falso = true;
        }
        for (int i = 0; i < valor.length(); i++) {
            if (valor.charAt(i) >= 48 && valor.charAt(i) <= 57 || valor.charAt(i) == 46 || valor.equals(" ") || valor.charAt(i) == 45) {
                falso = true;
            } else {
                falso = false;
            }
        }
        if (!falso) {
            JOptionPane.showMessageDialog(null, "Sólo se permiten números decimales. Vaya a la ayuda si sigue teniendo dudas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRotarManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRotarManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRotarManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRotarManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRotarManual(control).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel labelEjeX;
    private javax.swing.JLabel labelEjeY;
    private javax.swing.JLabel labelEjeZ;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField xValue;
    private javax.swing.JTextField yValue;
    private javax.swing.JTextField zValue;
    // End of variables declaration//GEN-END:variables

}
